# Generated by Django 4.2.6 on 2023-10-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231009_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addr',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='VeriCode',
        ),
        migrations.DeleteModel(
            name='Addr',
        ),
    ]
