# Generated by Django 4.2.6 on 2023-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.CharField(default=1, max_length=20, verbose_name='lesson'),
            preserve_default=False,
        ),
    ]
